services:
  ocis:
    image: owncloud/ocis-rolling:latest
    container_name: web
    entrypoint: /bin/sh
    command: ['-c', 'ocis init || true && ocis server']
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://localhost:9200
      OCIS_INSECURE: true
      OCIS_LOG_LEVEL: error
      IDM_ADMIN_PASSWORD: admin
      PROXY_ENABLE_BASIC_AUTH: true
      WEB_ASSET_APPS_PATH: /etc/ocis/webapps
    volumes:
      - ./dist:/etc/ocis/webapps:ro
